routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('/rss', function () {
    return view('user.gl-rss');
})->name('rssfeed');


Route::get('/card-carousel', function () {
	return view('card-carousel')->with('imgslide', \App\imgslide::all());
})->name('card-carousel');


Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home/team', 'HomeController@teamview')->name('team');

//Route::group(['middleware' => ['auth']], function () {
	Route::get('/home/topic', 'topicController@index')->name('topic');
	Route::get('/home/mytopic', 'topicController@mytopic')->name('mytopic');
	Route::get('/home/topic/addtopic', 'topicController@Showaddtopics')->name('showaddtopic');
	Route::post('/home/topic/addtopic', 'topicController@addtopic')->name('addtopic');
    Route::post('/home/topic/edittopic', 'topicController@edittopic')->name('edittopic');
    Route::post('/home/topic/addcomment', 'topicController@addcomment')->name('addcomment');
    Route::get('/home/topic/{id}', 'topicController@intopic')->name('intopic');
    Route::get('/home/topic/{id}/edit', 'topicController@showedittopic')->name('showedittopic');
    Route::post('/home/topic/report', 'topicController@report')->name('report');
    Route::post('/autocomplete','topicController@autocomplete');
    Route::post('/searchcontents','contentsController@searchcontents');
    Route::post('/searchcontentseng','contentsController@searchcontentseng');
//});

Route::get('/home/media', 'contentactController@indexuser')->name('media');
Route::get('/home/new', 'contentnewController@indexuser')->name('new');
Route::get('/home/media/{id}', 'contentactController@showuser')->name('showmedia');
Route::get('/home/result', 'resultController@indexuser')->name('result');
Route::get('/home/best', 'HomeController@best')->name('best');
Route::get('/home/content', 'contentsController@indexuser')->name('content');
Route::get("/home/contentre", function(){
    return View::make("user.contentre");
})->name('contentre');
Route::get("/home/contentf", function(){
    return View::make("user.contentf");
})->name('contentf');
Route::get("/home/contentn", function(){
    return View::make("user.contentn");
})->name('contentn');
Route::get('/home/eng', 'engController@indexuser')->name('eng');
Route::get('/showchangeprofile/{id}','HomeController@showchangeprofile')->name('showchangeprofile');
Route::get('/home/topic/deletetopic/{id}', 'topicController@deletetopic')->name('deletetopic');
Route::post('/changeprofile','HomeController@changeprofile')->name('changeprofile');

Route::group(['middleware' => ['admin']], function () {
	Route::get('/admin','adminController@index')->name('admin');
	Route::resource('/admin/contents','contentsController');
	Route::resource('/admin/contentact','contentactController');
	Route::resource('/admin/badwords','badwordController');
	Route::resource('/admin/menuheader','menuheaderController');
	Route::resource('/admin/best','bestController');
	Route::resource('/admin/contentnew','contentnewController');
	Route::get('/contentact/deletesome/{id}/{name}','contentactController@deletesome');
	Route::resource('/admin/link','linkController');
	Route::resource('/admin/eng','engController');
	Route::resource('/admin/result','resultController');
	Route::post('/admin/result/resulttable','resultController@resulttable')->name('resulttable');
	Route::resource('/admin/topic','topicBackController');
	Route::get('/admin/topic/report/{id}','topicBackController@showreports')->name('showreports');
	Route::get('/admin/topic/report/deleted/{id}/{type}','topicBackController@deletereports')->name('deletereports');
	Route::resource('/admin/team','teamController');
	Route::resource('/admin/imgslide','imgslideController');
	Route::post('/admin/banner','HomeController@banner')->name('banner');
	Route::delete('/admin/banner/{id}','HomeController@deletebanner')->name('deletebanner');
    Route::delete('/admin/contentsimg/{id}','contentsController@deleteimg');
    Route::get('/admin/homebanner', function () {
		return view('admin.homebanner');
	})->name('homebanner');
	Route::get('/admin/eng1', function () {
	    $data = \App\eng::where('category','Strategic plan')->get();
	    $img = \App\img::where('idfk','eng1')->first();
		return view('eng.index1',compact('data'),compact('img'));
	})->name('eng1');
	Route::get('/admin/eng2', function () {
        $data = \App\eng::where('category','Committee')->get();
        $img = \App\img::where('idfk','eng2')->first();
        return view('eng.index2',compact('data'),compact('img'));
    })->name('eng2');
	Route::get('/admin/eng3', function () {
        $data = \App\eng::where('category','M&E')->get();
        $img = \App\img::where('idfk','eng3')->first();
        return view('eng.index3',compact('data'),compact('img'));
    })->name('eng3');
	Route::get('/admin/eng4', function () {
        $data = \App\eng::where('category','Best practice')->get();
        $img = \App\img::where('idfk','eng4')->first();
        return view('eng.index4',compact('data'),compact('img'));
    })->name('eng4');
	Route::get('/userrole','userroleController@index')->name('userrole');
	Route::get('/userrole/delete/{id}','userroleController@delete');
	Route::get('/userrole/restore/{id}','userroleController@restore');
	Route::get('/userrole/changerole/{id}/{password}/{role}','userroleController@changerole');
	Route::get('/home/topic/closetopic/{id}', 'topicController@closetopic')->name('closetopic');
	Route::get('/home/topic/opentopic/{id}', 'topicController@opentopic')->name('opentopic');
});

Route::get('/files/{id}', 'contentactController@showpdf')->name('file.show');
Route::get('/showcontent/{id}', 'contentactController@showcontent')->name('showcontent');

Route::get('/admin/getchild/{name}','menuheaderController@getchild')->name('getchild');
Route::get('/admin/getchildinchild/{name}','menuheaderController@getchildinchild')->name('getchildinchild');

//Test page
Route::get("/test", function(){
    return View::make("test");
})->name('test');

//RSS feed
Route::get('feed/News', function() {
    $feedNews = App::make("feed");
    // cache the feed for 60 minutes with custom cache key "feedNewsKey"
    $feedNews->setCache(60, 'feedNewsKey1');
    // check if there is cached feed and build new only if is not
    if (!$feedNews->isCached()) {
    // creating rss feed with our most recent 20 records in news table
        $news = \DB::table('content_activity')->orderBy('updated_at', 'desc')->take(20)->get();
        $feedNews->title = 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข';
        $feedNews->description = 'ระบบเผยแพร่ข่าวสาร RSS';
        //        $feedNews->logo = 'http://yoursite.tld/logo.jpg';
        $feedNews->link = url('feedNews');
        $feedNews->setDateFormat('datetime'); // 'datetime', 'timestamp' or 'carbon'
        $feedNews->pubdate = $news[0]->updated_at; // date of latest news
        $feedNews->lang = 'th';
//        $feedNews->setShortening(true); // true or false if true can use setTextLimit
//        $feedNews->setTextLimit(100); // maximum length of description text
        foreach ($news as $n) {
            // set item's title, author, url, pubdate, description and content
            $feedNews->add($n->name, 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข', url('/home/media').'/'.$n->id, $n->created_at, $n->details, '');
        }
    }
    $feedNews->ctype = "text/xml";
    return $feedNews->render('rss');
});
Route::get('feed/News_activity', function() {
    $feedNews = App::make("feed");
    $feedNews->setCache(60, 'feedNewsKey2');
    if (!$feedNews->isCached()) {
        $news = \DB::table('content_activity')->where('category','ข่าวกิจกรรม')->orderBy('updated_at', 'desc')->take(20)->get();
        $feedNews->title = 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข';
        $feedNews->description = 'ระบบเผยแพร่ข่าวสาร RSS';
        $feedNews->link = url('feedNews');
        $feedNews->setDateFormat('datetime');
        $feedNews->pubdate = $news[0]->updated_at;
        $feedNews->lang = 'th';
//        $feedNews->setShortening(true);
//        $feedNews->setTextLimit(100);
        if (count($news) > 0){
            foreach ($news as $n) {
                $feedNews->add($n->name, 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข', url('/home/media').'/'.$n->id, $n->created_at, $n->details, '');
            }
        }
    }
    return $feedNews->render('rss');
});
Route::get('feed/News_release', function() {
    $feedNews = App::make("feed");
    $feedNews->setCache(60, 'feedNewsKey3');
    if (!$feedNews->isCached()) {
        $news = \DB::table('content_activity')->where('category','ข่าวประชาสัมพันธ์')->orderBy('updated_at', 'desc')->take(20)->get();
        $feedNews->title = 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข';
        $feedNews->description = 'ระบบเผยแพร่ข่าวสาร RSS';
        $feedNews->link = url('feedNews');
        $feedNews->setDateFormat('datetime');
        $feedNews->pubdate = $news[0]->updated_at;
        $feedNews->lang = 'th';
//        $feedNews->setShortening(true);
//        $feedNews->setTextLimit(100);
        if (count($news) > 0){
            foreach ($news as $n) {
                $feedNews->add($n->name, 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข', url('/home/media').'/'.$n->id, $n->created_at, $n->details, '');
            }
        }
    }

app/content.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class content extends Model
{
		protected $table='content';

		protected $fillable = [
			'name','fileuniq','active','category','edited_by'
		];

		public function file(){
			return $this->hasOne(files::class,'idfk','fileuniq');
		}
}

resources/views/content/create.blade.php
@extends('layouts.appadmin')
@section('content')
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
@include('layouts.onlyDatatable')
<style>

</style>
<form method="POST" action="{{ route('contents.store') }}" enctype="multipart/form-data">
	@csrf
	<div class="container py-1">
	<!--Section: Content-->
	<section class="px-md-6 mx-md-6 text-center text-lg-left dark-grey-text">
		<!--Grid row-->
		<div class="row d-flex justify-content-center">
			<!--Grid column-->
			<div class="col-md-12">
				<!-- Default form contact -->
				<form class="text-center" action="#!">
					<h3 align="center" class="font-weight-bold">เพิ่มข้อมูลแผนการป้องกัน</h3>
						<div class="row">
							<div class="col-4">
								<span>แสดงในหน้าหลัก</span>
								<input id="active" name="active" type="checkbox" data-toggle="toggle"
									   data-on="แสดง" data-off="ไม่แสดง" data-onstyle="success" data-offstyle="danger" data-style="slow"/>
							</div>
						</div>
						<div class="md-form">
							<input type="text" id="name" name="name" value="{{ old('name') }}" class="form-control col-md-12" autocomplete="off" required>
							<label for="name">ชื่อ</label>
						</div>
						<select class="browser-default custom-select" name="category">
							<option selected disabled hidden>ประเภทข้อมูล</option>
							<option value="0">2560 - 2564</option>
							<option value="1">ฉบับปรับปรุง</option>
							<option value="2">นโยบายเร่งรัด</option>
							<option value="6">แผนปฏิรูปด้าน NCDs</option>
						</select>
						<div class="md-form">
							<div class="custom-file">
								<input type="text" id="file" name="file" value="{{ old('file') }}" class="form-control col-md-12" autocomplete="off">
								<label for="file">ลิ้งไฟล์</label>
							</div>
						<!-- Send button -->
							<button class="btn btn-info btn-block" type="submit">บันทึก</button>
						</div>
				</form>
				<!-- Default form contact -->
			</div>
			<!--Grid column-->
		</div>
		<!--Grid row-->
	</section>
	<!--Section: Content-->
</div>
</form>
@endsection

resources/views/content/edit.blade.php
@extends('layouts.appadmin')
@section('content')
@include('layouts.onlyDatatable')
<style>

</style>
	<form method="POST" action=" {{route('contents.update',$model->id)}}" enctype="multipart/form-data">
		@csrf
		<div class="container-fluid py-1">
			<!--Section: Content-->
			<section class="px-md-6 mx-md-6 text-center text-lg-left dark-grey-text">
				<!--Grid row-->
				<div class="row d-flex justify-content-center">
					<!--Grid column-->
					<div class="col-md-12">
						<!-- Default form contact -->
						<form class="text-center" action="#!">
							<h3 align="center" class="font-weight-bold">แก้ไขข้อมูลแผนการป้องกัน</h3>
							<div class="row">
								<div class="col-4">
									<span>แสดงในหน้าหลัก</span>
									<input id="active" name="active" type="checkbox" data-toggle="toggle"
									       data-on="แสดง" data-off="ไม่แสดง" data-onstyle="success" data-offstyle="danger" data-style="slow" {{$model->active == 1 ? 'checked':''}}/>
								</div>
							</div>
							<!-- Name -->
							<div class="md-form">
								<i role="presentation"  class="fas fa-heading prefix"></i>
								<input type="text" id="name" name="name" value="{{$model->name}}" class="form-control col-md-12" autocomplete="off" required>
								<label for="name">ชื่อ</label>
							</div>
							<select class="browser-default custom-select" name="category">
								<option selected disabled hidden>ประเภทข้อมูล</option>
								<option {{$model->category == 0 ? "selected":''}} value="0">2560 - 2564</option>
								<option {{$model->category == 1 ? "selected":''}} value="1">ฉบับปรับปรุง</option>
								<option {{$model->category == 2 ? "selected":''}} value="2">นโยบายเร่งรัด</option>
								<option {{$model->category == 6 ? "selected":''}} value="6">แผนปฏิรูปด้าน NCDs</option>
							</select>
							<div class="md-form">
								<div class="custom-file">
									<input type="text" id="file" name="file" value="{{$model->fileuniq}}" class="form-control col-md-12" autocomplete="off">
									<label for="file">ลิ้งไฟล์</label>
								</div>
								<script type="text/javascript">
                  function readURL(input) {
                    if (input.files && input.files[0]) {
                      var reader = new FileReader();
                      reader.onload = function (e) {
                        $('#profile-img-tag').attr('src', e.target.result);
                      };
                      reader.readAsDataURL(input.files[0]);
                    }
                  }
                  $("#img").change(function(){
                    readURL(this);
                  });
								</script>
								<!-- Send button -->
								{{ method_field('PUT') }}
							</div>
							<button class="btn btn-info btn-block" type="submit">บันทึก</button>
						</form>
						<!-- Default form contact -->
					</div>
					<!--Grid column-->
				</div>
				<!--Grid row-->
			</section>
			<!--Section: Content-->
		</div>
	</form>
@endsection

resources/views/content/sub1.blade.php
<script type="text/javascript" src="{{ URL::asset('CKEditor/ckeditor.js') }}"></script>
@include('layouts.onlyDatatable')
<form method="POST" action=" {{route('contents.store')}}" enctype="multipart/form-data">
    @csrf
    <input style="display: none" value="0" name="category">
    <div class="row">
        <div class="col-5 offset-1" align="center">
            @if($data['img'] == null || $data['img']->path == "null")
                <label id="uploadimg" for="img" style="
                        min-width: 100%;
                        min-height: 320px;
                        background-image:url('{{ asset('Defaultimg/imgupload.svg') }}');
                        background-size:100% 100%;
                        cursor: pointer">
                    <span id="previewImg"></span>
                </label>
            @else
                <label id="uploadimg" for="img" style="
                        min-width: 100%;
                        min-height: 320px;
                        height: auto;
                        background-image:url('{{ asset('/uploads/'.$data['img']->path) }}');
                        background-size:100% 100%;
                        cursor: pointer">
                    <span id="previewImg"></span>
                </label>
            @endif
        </div>
        <div class="col-6">
            {{--<h3>ลิ้งดาวน์โหลดทั้งหมด</h3>--}}
            {{--<div>--}}
                {{--<input type="text" id="downloadall" name="downloadall" value="{{$data['dall1']!=null&&$data['dall1']->fileuniq!=null ? $data['dall1']->fileuniq:''}}" class="form-control col-12" autocomplete="off">--}}
                {{--<label for="downloadall">ลิ้ง URL</label>--}}
            {{--</div>--}}
            <h3>คำอธิบาย*:</h3>
            <textarea id="details1" class="details" name="detailbanner">{{$data['img']!=null&&$data['img']->name!=null ? $data['img']->name:''}}
                        </textarea>
            <script>
                var CSRFToken = $('meta[name="csrf-token"]').attr('content');
                var options = {
                    filebrowserImageBrowseUrl: '{{$site}}/laravel-filemanager?type=Images',
                    filebrowserImageUploadUrl: '{{$site}}/laravel-filemanager/upload?type=Images&_token='+CSRFToken,
                    filebrowserBrowseUrl: '{{$site}}/laravel-filemanager?type=Files',
                    filebrowserUploadUrl: '{{$site}}/laravel-filemanager/upload?type=Files&_token='+CSRFToken,
                };
            </script>
            <script>
                CKEDITOR.replace('details1', options);
            </script>
            {{--<textarea class="form-control" name="detailbanner" autoComplete="off" placeholder="ใส่รายละเอียด" rows="4">{{$data['img']!=null&&$data['img']->name!=null ? $data['img']->name:''}}</textarea>--}}
            <h4>อัพโหลดไฟล์*:
                <div class="float-right">
                    <span onclick="confirmdelete('{{$data['img']!=null&&$data['img']->id!=null?$data['img']->id : null}}');" class="btn btn-outline-dark-green btn-sm" style="border-radius: 20px;">ลบ</span>
                    <button type="submit" class="btn btn-outline-dark-green btn-sm" style="border-radius: 20px;">อัพโหลด</button>
                </div>
            </h4>
            <h6 style="color:#203F54">*รองรับ JPEG, PNG</h6>
            <h6 style="color:#203F54">*ขนาดไฟล์ไม่เกิน 378*522 px(A4)</h6>
        </div>
    </div>
    <input onchange="preview(this);" style="display: none" type="file" class="custom-file-input @error('img') is-invalid @enderror" id="img" name="img" accept="image/*">
    <script type="text/javascript">
        window.preview = function (input) {
            if (input.files && input.files[0]) {
                $("#previewImg").html("");
                $(input.files).each(function () {
                    var reader = new FileReader();
                    reader.readAsDataURL(this);
                    reader.onload = function (e) {
                        $("#previewImg").append("<img class='thumb' style=\"max-height: 330px;max-width: 100%;\" src='" + e.target.result + "'>");
                    }
                });
                document.getElementById("uploadimg").style.backgroundImage = 'none';
            }
        };
    </script>
</form>
<hr>
<form method="POST" action=" {{route('contents.store')}}" enctype="multipart/form-data">
    @csrf
    <input style="display: none" value="3" name="category">
    <div class="row">
        <div class="col-5 offset-1" align="center">
            @if($data['img3'] == null || $data['img3']->path == "null")
                <label id="uploadimg3" for="img3" style="
                        min-width: 100%;
                        min-height: 320px;
                        background-image:url('{{ asset('Defaultimg/imgupload.svg') }}');
                        background-size:100% 100%;
                        cursor: pointer">
                    <span id="previewImg3"></span>
                </label>
            @else
                <label id="uploadimg3" for="img3" style="
                        min-width: 100%;
                        min-height: 320px;
                        height: auto;
                        background-image:url('{{ asset('/uploads/'.$data['img3']->path) }}');
                        background-size:100% 100%;
                        cursor: pointer">
                    <span id="previewImg3"></span>
                </label>
            @endif
        </div>
        <div class="float-right">
            <span>รูปภาพหน้าแรก</span>
            <h6 style="color:#203F54">*รองรับ JPEG, PNG</h6>
            <h6 style="color:#203F54">*ขนาดไฟล์ไม่เกิน 1000*1000 px(1:1)</h6>
            <button type="submit" class="btn btn-outline-dark-green btn-sm" style="border-radius: 20px;">อัพโหลด</button>
        </div>
    </div>
    <input onchange="preview3(this);" style="display: none" type="file" class="custom-file-input @error('img') is-invalid @enderror" id="img3" name="img" accept="image/*">
    <script type="text/javascript">
        window.preview3 = function (input) {
            if (input.files && input.files[0]) {
                $("#previewImg3").html("");
                $(input.files).each(function () {
                    var reader = new FileReader();
                    reader.readAsDataURL(this);
                    reader.onload = function (e) {
                        $("#previewImg3").append("<img class='thumb' style=\"max-height: 330px;max-width: 100%;\" src='" + e.target.result + "'>");
                    }
                });
                document.getElementById("uploadimg3").style.backgroundImage = 'none';
            }
        };
    </script>

</form>
<br/>
<table id="contenttable" class="table table-striped table-bordered" style="width:100%">
    <thead>
    <tr>
        <th>ไอดี</th>
        <th>ชื่อหัวข้อ</th>
        <th>ไฟล์</th>
    </tr>
    </thead>
    <tbody>
    @foreach($data['data'] as $row)
        <tr>
            <td>{{$row->id}}</td>
            <td>{{$row->name}}</td>
            <td>
                @if($row->fileuniq === null)
                    ไม่พบลิ้ง
                @else
                    <a href="{{$row->fileuniq}}" target="_blank">{{$row->fileuniq}}</a>
                @endif
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
<script type="text/javascript">
    let id = 0;
    $(document).ready(function() {
        let table = $('#contenttable').DataTable({
            lengthChange: false,
            columnDefs: [
                {
                    "targets": [ 0 ],
                    "visible": false,
                    "searchable": false
                },
            ],
            "pageLength": 5,
            "pagingType": "full_numbers",
            buttons: [
                {
                    text: 'เพิ่มข้อมูล',
                    action: function ( e, dt, node, config ) {
                        window.location.href = "{{route('contents.create')}}";
                    },
                },
                {
                    text: 'แก้ไขข้อมูล',
                    action: function ( e, dt, node, config) {
                        $('#contenttable .selected').each(function() {
                            window.location.href = './contents/'+id[0]+'/edit';
                        });
                    }
                },
                {
                    text: 'ลบข้อมูล',
                    action: function ( e, dt, node, config) {
                        $('#contenttable .selected').each(function() {
                            Swal.fire({
                                title: 'คุณแน่ใจที่จะลบ ?',
                                text: "โปรดดูให้แน่ใจว่าที่เลือกนั้นถูกต้อง !",
                                icon: 'warning',
                                showCancelButton: true,
                                confirmButtonColor: '#3085d6',
                                cancelButtonColor: '#d33',
                                confirmButtonText: 'ใช่ ลบเลย !',
                                cancelButtonText : 'ยกเลิก'
                            }).then((result) => {
                                if (result.value) {
                                    goDelete();
                                    table.row('.selected').remove().draw( false );
                                }
                            })
                        });
                    }
                }
            ],
            responsive: true,
            "language": {
                "sEmptyTable":     "ไม่มีข้อมูลในตาราง",
                "sInfo":           "แสดง _START_ ถึง _END_ จาก _TOTAL_ แถว",
                "sInfoEmpty":      "แสดง 0 ถึง 0 จาก 0 แถว",
                "sInfoFiltered":   "(กรองข้อมูล _MAX_ ทุกแถว)",
                "sInfoPostFix":    "",
                "sInfoThousands":  ",",
                "sLengthMenu":     "แสดง _MENU_ แถว",
                "sLoadingRecords": "กำลังโหลดข้อมูล...",
                "sProcessing":     "กำลังดำเนินการ...",
                "sSearch":         "ค้นหา: ",
                "sZeroRecords":    "ไม่พบข้อมูล",
                "oPaginate": {
                    "sFirst":    "หน้าแรก",
                    "sPrevious": "ก่อนหน้า",
                    "sNext":     "ถัดไป",
                    "sLast":     "หน้าสุดท้าย"
                },
                "oAria": {
                    "sSortAscending":  ": เปิดใช้งานการเรียงข้อมูลจากน้อยไปมาก",
                    "sSortDescending": ": เปิดใช้งานการเรียงข้อมูลจากมากไปน้อย"
                }
            },
            "drawCallback": function( settings ) {
                console.log(settings.aiDisplay.length);
            }
        });
        table.buttons().container().appendTo( '#contenttable_wrapper .col-md-6:eq(0)' );
        $('#contenttable tbody').on( 'click', 'tr', function () {
            if ( $(this).hasClass('selected') ) {
                $(this).removeClass('selected');
            }
            else {
                table.$('tr.selected').removeClass('selected');
                $(this).addClass('selected');
            }
        } );
        $('#contenttable').on( 'click', 'tr', function () {
            id = table.row( this ).data();
        } );

        function goDelete() {
            let _token = $('input[name="_token"]').val();
            $.ajax(
                {
                    type: "DELETE",
                    url: "{{ route('contents.store') }}"+'/'+id[0],
                    data:{ _token:_token  },
                    success: function (data) {
                        Swal.fire({
                            position: 'top-end',
                            icon: 'success',
                            title: 'ข้อมูลถูกลบแล้ว',
                            showConfirmButton: false,
                            timer: 3000
                        })
                    },
                    error: function (data) {
                        Swal.fire({
                            icon: 'error',
                            title: 'อุ๊บบ...',
                            text: 'มีบางอย่างผิดพลาด !'
                        })
                    }
                });
        }


    } );

    function confirmdelete(id) {
        Swal.fire({
            title: 'คุณแน่ใจที่จะลบ ?',
            text: "รูปและคำอธิบายจะหายไป !",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'ใช่ ลบเลย !',
            cancelButtonText : 'ยกเลิก'
        }).then((result) => {
            if (result.value) {
                deleteimg(id);
            }
        })
    };

    function deleteimg(id) {
        let _token = $('input[name="_token"]').val();
        if(id){
            $.ajax(
                {
                    type: "DELETE",
                    url: "{{$site}}/admin/contentsimg/"+id,
                    data:{ _token:_token  },
                    success: function (data) {
                        Swal.fire({
                            position: 'top-end',
                            icon: 'success',
                            title: 'ข้อมูลถูกลบแล้ว',
                            showConfirmButton: false,
                            timer: 3000
                        });
                        setTimeout(function(){ window.location.reload(); }, 1000);
                    },
                    error: function (data) {
                        console.log(data);
                        Swal.fire({
                            icon: 'error',
                            title: data.error,
                            text: 'มีบางอย่างผิดพลาด !'
                        })
                    }
                });
        }
    };
</script>