routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('/rss', function () {
    return view('user.gl-rss');
})->name('rssfeed');


Route::get('/card-carousel', function () {
	return view('card-carousel')->with('imgslide', \App\imgslide::all());
})->name('card-carousel');


Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home/team', 'HomeController@teamview')->name('team');

//Route::group(['middleware' => ['auth']], function () {
	Route::get('/home/topic', 'topicController@index')->name('topic');
	Route::get('/home/mytopic', 'topicController@mytopic')->name('mytopic');
	Route::get('/home/topic/addtopic', 'topicController@Showaddtopics')->name('showaddtopic');
	Route::post('/home/topic/addtopic', 'topicController@addtopic')->name('addtopic');
    Route::post('/home/topic/edittopic', 'topicController@edittopic')->name('edittopic');
    Route::post('/home/topic/addcomment', 'topicController@addcomment')->name('addcomment');
    Route::get('/home/topic/{id}', 'topicController@intopic')->name('intopic');
    Route::get('/home/topic/{id}/edit', 'topicController@showedittopic')->name('showedittopic');
    Route::post('/home/topic/report', 'topicController@report')->name('report');
    Route::post('/autocomplete','topicController@autocomplete');
    Route::post('/searchcontents','contentsController@searchcontents');
    Route::post('/searchcontentseng','contentsController@searchcontentseng');
//});

Route::get('/home/media', 'contentactController@indexuser')->name('media');
Route::get('/home/new', 'contentnewController@indexuser')->name('new');
Route::get('/home/media/{id}', 'contentactController@showuser')->name('showmedia');
Route::get('/home/result', 'resultController@indexuser')->name('result');
Route::get('/home/best', 'HomeController@best')->name('best');
Route::get('/home/content', 'contentsController@indexuser')->name('content');
Route::get("/home/contentre", function(){
    return View::make("user.contentre");
})->name('contentre');
Route::get("/home/contentf", function(){
    return View::make("user.contentf");
})->name('contentf');
Route::get("/home/contentn", function(){
    return View::make("user.contentn");
})->name('contentn');
Route::get('/home/eng', 'engController@indexuser')->name('eng');
Route::get('/showchangeprofile/{id}','HomeController@showchangeprofile')->name('showchangeprofile');
Route::get('/home/topic/deletetopic/{id}', 'topicController@deletetopic')->name('deletetopic');
Route::post('/changeprofile','HomeController@changeprofile')->name('changeprofile');

Route::group(['middleware' => ['admin']], function () {
	Route::get('/admin','adminController@index')->name('admin');
	Route::resource('/admin/contents','contentsController');
	Route::resource('/admin/contentact','contentactController');
	Route::resource('/admin/badwords','badwordController');
	Route::resource('/admin/menuheader','menuheaderController');
	Route::resource('/admin/best','bestController');
	Route::resource('/admin/contentnew','contentnewController');
	Route::get('/contentact/deletesome/{id}/{name}','contentactController@deletesome');
	Route::resource('/admin/link','linkController');
	Route::resource('/admin/eng','engController');
	Route::resource('/admin/result','resultController');
	Route::post('/admin/result/resulttable','resultController@resulttable')->name('resulttable');
	Route::resource('/admin/topic','topicBackController');
	Route::get('/admin/topic/report/{id}','topicBackController@showreports')->name('showreports');
	Route::get('/admin/topic/report/deleted/{id}/{type}','topicBackController@deletereports')->name('deletereports');
	Route::resource('/admin/team','teamController');
	Route::resource('/admin/imgslide','imgslideController');
	Route::post('/admin/banner','HomeController@banner')->name('banner');
	Route::delete('/admin/banner/{id}','HomeController@deletebanner')->name('deletebanner');
    Route::delete('/admin/contentsimg/{id}','contentsController@deleteimg');
    Route::get('/admin/homebanner', function () {
		return view('admin.homebanner');
	})->name('homebanner');
	Route::get('/admin/eng1', function () {
	    $data = \App\eng::where('category','Strategic plan')->get();
	    $img = \App\img::where('idfk','eng1')->first();
		return view('eng.index1',compact('data'),compact('img'));
	})->name('eng1');
	Route::get('/admin/eng2', function () {
        $data = \App\eng::where('category','Committee')->get();
        $img = \App\img::where('idfk','eng2')->first();
        return view('eng.index2',compact('data'),compact('img'));
    })->name('eng2');
	Route::get('/admin/eng3', function () {
        $data = \App\eng::where('category','M&E')->get();
        $img = \App\img::where('idfk','eng3')->first();
        return view('eng.index3',compact('data'),compact('img'));
    })->name('eng3');
	Route::get('/admin/eng4', function () {
        $data = \App\eng::where('category','Best practice')->get();
        $img = \App\img::where('idfk','eng4')->first();
        return view('eng.index4',compact('data'),compact('img'));
    })->name('eng4');
	Route::get('/userrole','userroleController@index')->name('userrole');
	Route::get('/userrole/delete/{id}','userroleController@delete');
	Route::get('/userrole/restore/{id}','userroleController@restore');
	Route::get('/userrole/changerole/{id}/{password}/{role}','userroleController@changerole');
	Route::get('/home/topic/closetopic/{id}', 'topicController@closetopic')->name('closetopic');
	Route::get('/home/topic/opentopic/{id}', 'topicController@opentopic')->name('opentopic');
});

Route::get('/files/{id}', 'contentactController@showpdf')->name('file.show');
Route::get('/showcontent/{id}', 'contentactController@showcontent')->name('showcontent');

Route::get('/admin/getchild/{name}','menuheaderController@getchild')->name('getchild');
Route::get('/admin/getchildinchild/{name}','menuheaderController@getchildinchild')->name('getchildinchild');

//Test page
Route::get("/test", function(){
    return View::make("test");
})->name('test');

//RSS feed
Route::get('feed/News', function() {
    $feedNews = App::make("feed");
    // cache the feed for 60 minutes with custom cache key "feedNewsKey"
    $feedNews->setCache(60, 'feedNewsKey1');
    // check if there is cached feed and build new only if is not
    if (!$feedNews->isCached()) {
    // creating rss feed with our most recent 20 records in news table
        $news = \DB::table('content_activity')->orderBy('updated_at', 'desc')->take(20)->get();
        $feedNews->title = 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข';
        $feedNews->description = 'ระบบเผยแพร่ข่าวสาร RSS';
        //        $feedNews->logo = 'http://yoursite.tld/logo.jpg';
        $feedNews->link = url('feedNews');
        $feedNews->setDateFormat('datetime'); // 'datetime', 'timestamp' or 'carbon'
        $feedNews->pubdate = $news[0]->updated_at; // date of latest news
        $feedNews->lang = 'th';
//        $feedNews->setShortening(true); // true or false if true can use setTextLimit
//        $feedNews->setTextLimit(100); // maximum length of description text
        foreach ($news as $n) {
            // set item's title, author, url, pubdate, description and content
            $feedNews->add($n->name, 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข', url('/home/media').'/'.$n->id, $n->created_at, $n->details, '');
        }
    }
    $feedNews->ctype = "text/xml";
    return $feedNews->render('rss');
});
Route::get('feed/News_activity', function() {
    $feedNews = App::make("feed");
    $feedNews->setCache(60, 'feedNewsKey2');
    if (!$feedNews->isCached()) {
        $news = \DB::table('content_activity')->where('category','ข่าวกิจกรรม')->orderBy('updated_at', 'desc')->take(20)->get();
        $feedNews->title = 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข';
        $feedNews->description = 'ระบบเผยแพร่ข่าวสาร RSS';
        $feedNews->link = url('feedNews');
        $feedNews->setDateFormat('datetime');
        $feedNews->pubdate = $news[0]->updated_at;
        $feedNews->lang = 'th';
//        $feedNews->setShortening(true);
//        $feedNews->setTextLimit(100);
        if (count($news) > 0){
            foreach ($news as $n) {
                $feedNews->add($n->name, 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข', url('/home/media').'/'.$n->id, $n->created_at, $n->details, '');
            }
        }
    }
    return $feedNews->render('rss');
});
Route::get('feed/News_release', function() {
    $feedNews = App::make("feed");
    $feedNews->setCache(60, 'feedNewsKey3');
    if (!$feedNews->isCached()) {
        $news = \DB::table('content_activity')->where('category','ข่าวประชาสัมพันธ์')->orderBy('updated_at', 'desc')->take(20)->get();
        $feedNews->title = 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข';
        $feedNews->description = 'ระบบเผยแพร่ข่าวสาร RSS';
        $feedNews->link = url('feedNews');
        $feedNews->setDateFormat('datetime');
        $feedNews->pubdate = $news[0]->updated_at;
        $feedNews->lang = 'th';
//        $feedNews->setShortening(true);
//        $feedNews->setTextLimit(100);
        if (count($news) > 0){
            foreach ($news as $n) {
                $feedNews->add($n->name, 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข', url('/home/media').'/'.$n->id, $n->created_at, $n->details, '');
            }
        }
    }

resources/views/admin/homebanner.blade.php
@extends('layouts.appadmin')
<style>
	html { height: 100%; width: 100%;}
	body { height: 100%; width: 100%;}
</style>
<?php
$banner1 = \DB::table('homebanner')->where('url','1')->first();
if($banner1)$path1 = json_decode($banner1->path);
else $path1 = null;
$banner2 = \DB::table('homebanner')->where('url','2')->first();
if($banner2)$path2 = json_decode($banner2->path);
else $path2 = null;
?>
@section('content')
<div class="col">
	<span class="font-weight-bold">การจัดการแบนเนอร์</span>
	<div class="float-right">
		<a style="border-radius: 40px;padding: 5px 30px;background-color: #203F54" class="btn" tabindex="0" onclick="confirmdelete('{{$banner1 != null ? $banner1->id:null}}');">ลบ</a>
		<a style="border-radius: 40px;padding: 5px 30px;background-color: #203F54" class="btn" data-toggle="modal" data-target="#createModal">เปลี่ยนข้อมูล</a>
	</div>
</div>
<br>
<img style="cursor: pointer;" tabindex="0" onclick="window.open('{{$path1 != null ? $path1[1]:''}}');" src="{{$path1 != null && $path1[0] != null ? $site.'/uploads/'.$path1[0]:$site.'/Defaultimg/noimg.jpg'}}" width="100%" height="200px" alt="banner1">
<div class="col">
	<br>
	<div class="float-right" style="width: 70%;font-size: 16px">
		<label style="float: left;" for="url">Link Url: </label>
		<span style="overflow: hidden;display: block;padding: 0 4px 0 10px;"><input style="width: 100%;" type="text" value="{{$path1 != null ? $path1[1]:''}}" readonly></span>
	</div>
	<span style="font-size: 14px">ภาพแบนเนอร์*</span>
	<p style="color: #01673F;font-size: 12px;margin: 0">*รองรับ JPEG, PNG</p>
	<p style="color: #01673F;font-size: 12px">*ขนาดไฟล์ไม่เกิน 5335 * 680 px(19:2.4)</p>
</div>

{{--modal-banner--}}
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="createModalLabel" id="createModal">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="createModalLabel">เปลี่ยนข้อมูล</h4>
				<button type="button" name="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>

			<div class="modal-body">
				<form method="POST" action="{{ route('banner') }}" enctype="multipart/form-data">
					@csrf
					<input value="{{$banner1 != null ? $banner1->id:''}}" name="id" hidden>
					<input value="1" name="category" hidden>
					<div class="form-group row justify-content-center">
						<div class="col-md-10 text-center">
							<label for="url">Link Url</label>
							<div class="input-group mb-3 input-icons">
								<input style="border-radius: 3rem;border-color: #01673F" type="text" class="form-control input-field" placeholder="Link Url" aria-label="Link Url" id="url" name="url" autocomplete="off" value="{{$path1 != null ? $path1[1]:''}}">
							</div>
						</div>
					</div>

					<div class="form-group row justify-content-center">
						<div class="col-md-10 text-center">
							<label for="img">รูปแบนเนอร์</label>
							<div class="input-group mb-3 input-icons">
								<label for="img" class="form-control" style="border-radius: 3rem;border-color: #01673F">เพิ่มรูปภาพ</label>
								<input style="border-radius: 3rem;border-color: #01673F;display: none" type="file" class="form-control input-field" placeholder="รูปภาพ" aria-label="รูปภาพ" id="img" name="img" autocomplete="off">
							</div>
						</div>
					</div>

					<div class="form-group row justify-content-center">
						<div class="col-md-8">
							<button style="border-radius: 3rem;background-color:#01673F ;color: white;" type="submit" class="btn btn-block">
								{{ __('เปลี่ยนข้อมูล') }}
							</button>
						</div>
					</div>
				</form>

			</div>
		</div>
	</div>
</div>

<div class="col">
	<span class="font-weight-bold">การจัดการแบนเนอร์ (ภาษาอังกฤษ)</span>
	<div class="float-right">
		<a style="border-radius: 40px;padding: 5px 30px;background-color: #203F54" class="btn" tabindex="0" onclick="confirmdelete('{{$banner2 != null ? $banner2->id:null}}');">ลบ</a>
		<a style="border-radius: 40px;padding: 5px 30px;background-color: #203F54" class="btn" data-toggle="modal" data-target="#createModal1">เปลี่ยนข้อมูล</a>
	</div>
</div>
<br>
<img style="cursor: pointer;" tabindex="0" onclick="window.open('{{$path2 != null ? $path2[1]:''}}');" src="{{$path2 != null && $path2[0] != null ? $site.'/uploads/'.$path2[0]:$site.'/Defaultimg/noimg.jpg'}}" width="100%" height="200px">
<div class="col">
	<br>
	<div class="float-right" style="width: 70%;font-size: 16px">
		<label style="float: left;" for="url">Link Url: </label>
		<span style="overflow: hidden;display: block;padding: 0 4px 0 10px;"><input style="width: 100%;" type="text" value="{{$path2 != null ? $path2[1]:''}}" readonly></span>
	</div>
	<span style="font-size: 14px">ภาพแบนเนอร์*</span>
	<p style="color: #01673F;font-size: 12px;margin: 0">*รองรับ JPEG, PNG</p>
	<p style="color: #01673F;font-size: 12px">*ขนาดไฟล์ไม่เกิน 5335 * 680 px(19:2.4)</p>
</div>

{{--modal-banner--}}
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="createModal1Label" id="createModal1">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title" id="createModal1Label">เปลี่ยนข้อมูล</h4>
				<button type="button" name="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>

			<div class="modal-body">
				<form method="POST" action="{{ route('banner') }}" enctype="multipart/form-data">
					@csrf
					<input value="{{$banner2 != null ? $banner2->id:''}}" name="id" hidden>
					<input value="2" name="category" hidden>
					<div class="form-group row justify-content-center">
						<div class="col-md-10 text-center">
							<label for="url2">Link Url</label>
							<div class="input-group mb-3 input-icons">
								<input style="border-radius: 3rem;border-color: #01673F" type="text" class="form-control input-field" placeholder="Link Url" aria-label="Link Url" id="url2" name="url" autocomplete="off" value="{{$path2 != null ? $path2[1]:''}}">
							</div>
						</div>
					</div>

					<div class="form-group row justify-content-center">
						<div class="col-md-10 text-center">
							<label for="img">รูปแบนเนอร์</label>
							<div class="input-group mb-3 input-icons">
								<label for="img2" class="form-control" style="border-radius: 3rem;border-color: #01673F">เพิ่มรูปภาพ</label>
								<input style="border-radius: 3rem;border-color: #01673F;display: none" type="file" class="form-control input-field" placeholder="รูปภาพ" aria-label="รูปภาพ" id="img2" name="img" autocomplete="off">
							</div>
						</div>
					</div>

					<div class="form-group row justify-content-center">
						<div class="col-md-8">
							<button style="border-radius: 3rem;background-color:#01673F ;color: white;" type="submit" class="btn btn-block">
								{{ __('เปลี่ยนข้อมูล') }}
							</button>
						</div>
					</div>
				</form>

			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
    function confirmdelete(id) {
        Swal.fire({
            title: 'คุณแน่ใจที่จะลบ ?',
            text: "รูปและลิ้งจะหายไป !",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'ใช่ ลบเลย !',
            cancelButtonText : 'ยกเลิก'
        }).then((result) => {
            if (result.value) {
                deleteimg(id);
            }
        })
    };

    function deleteimg(id) {
        let _token = $('input[name="_token"]').val();
        if(id){
            $.ajax(
			{
				type: "DELETE",
				url: "{{$site}}/admin/banner/"+id,
				data:{ _token:_token  },
				success: function (data) {
					Swal.fire({
						position: 'top-end',
						icon: 'success',
						title: 'ข้อมูลถูกลบแล้ว',
						showConfirmButton: false,
						timer: 3000
					});
					setTimeout(function(){ window.location.reload(); }, 1000);
				},
				error: function (data) {
					Swal.fire({
						icon: 'error',
						title: data.error,
						text: 'มีบางอย่างผิดพลาด !'
					})
				}
			});
        }
    };
</script>
@endsection

resources/views/admin/index.blade.php
@extends('layouts.appadmin')
<style>

</style>
@section('content')
	<div class="container-fluid">

	</div>
@endsection
<script type="text/javascript">

</script>

resources/views/admin/menuleft.blade.php
<style>
	.nav-right{
		background: white;
		box-shadow: inset 0px 0px 10px rgba(0, 0, 0, 0.25);
	}
	.nav-link.active {
		color:#01673F;
		background-color: #E5E5E5;
	}
	a img{
		margin: 4px 10px 4px 0;
		width: 36px;
		height: 30px;
	}
	img.active{
		filter: invert(29%) sepia(23%) saturate(2325%) hue-rotate(114deg) brightness(94%) contrast(99%);
	}
	.submenu{
		padding: 10px 0 10px 63px;
	}

	[data-toggle="collapse"]:after {
		display: inline-block;
		font-family: "Font Awesome 5 Free", serif;
		font-weight: 900;
		font-size: 25px;
		text-rendering: auto;
		-webkit-font-smoothing: antialiased;
		-moz-osx-font-smoothing: grayscale;
		content: "\f0d7";
		transform: rotate(180deg) ;
		transition: all linear 0.25s;
		float: right;
		position: relative;
		top: 3px;
	}
	[data-toggle="collapse"].collapsed:after {
		transform: rotate(0deg) ;
	}
</style>
<div class="list-group nav-right" id="accordion">
	<a data-toggle="collapse" data-target="#homeadmin" aria-expanded="true" class="nav-link collapsed" aria-controls="homeadmin"><img src="{{$site}}/Defaultimg/1.svg" alt="หน้าหลัก">หน้าหลัก</a>
	<p class="sub-menu collapse {{ Route::current()->getName() == 'homebanner' || Route::current()->getName() == 'imgslide.index'
	? "show" : "" }}" id="homeadmin" data-parent="#accordion">
		<a href="{{ route('homebanner') }}" class="nav-link submenu {{ Route::current()->getName() == 'homebanner' ? "active" : "" }}">แบนเนอร์</a>
		<a href="{{ route('imgslide.index') }}" class="nav-link submenu {{ Route::current()->getName() == 'imgslide.index' ? "active" : "" }}">พื้นที่นำเสนอ</a>
	</p>
	<a href="{{ route('team.index') }}" class="nav-link {{ Route::current()->getName() == 'team.index' ? "active" : "" }}"><img src="{{$site}}/Defaultimg/2.svg" alt="หน้าหลัก">คณะกรรมการ</a>
	<a href="{{ route('contents.index') }}" class="nav-link {{ Route::current()->getName() == 'contents.index' ? "active" : "" }}"><img src="{{$site}}/Defaultimg/3.svg" alt="แผนการป้องกันและควบคุมโรคไม่ติดต่อ">แผนการป้องกันและควบคุมโรคไม่ติดต่อ 5 ปี (พ.ศ. 2560 - 2564)</a>
	<a href="{{ route('result.index') }}" class="nav-link {{ Route::current()->getName() == 'result.index' ? "active" : "" }}"><img src="{{$site}}/Defaultimg/4.svg" alt="ผลการดำเนินงาน">ผลการดำเนินงาน</a>
	<a href="{{ route('best.index') }}" class="nav-link {{ Route::current()->getName() == 'best.index' ? "active" : "" }}"><img src="{{$site}}/Defaultimg/best.svg" alt="Best practice">Best practice</a>
	<a href="{{ route('contentnew.index') }}" class="nav-link {{ Route::current()->getName() == 'contentnew.index' ? "active" : "" }}"><img src="{{$site}}/Defaultimg/6.svg" alt="ข่าวสาร">ข่าวสาร</a>
	<a href="{{ route('contentact.index') }}" class="nav-link {{ Route::current()->getName() == 'contentact.index' ? "active" : "" }}"><img src="{{$site}}/Defaultimg/7.svg" alt="สื่อเผยแพร่">สื่อเผยแพร่</a>
	<a href="{{ route('topic.index') }}" class="nav-link {{ Route::current()->getName() == 'topic.index' ? "active" : "" }}"><img src="{{$site}}/Defaultimg/question.svg" alt="กระดานสนทนา">กระดานสนทนา</a>
	<a href="{{ route('link.index') }}" class="nav-link {{ Route::current()->getName() == 'link.index' ? "active" : "" }}"><img src="{{$site}}/Defaultimg/link.svg" alt="หน่วยงานที่เกี่ยวข้อง">หน่วยงานที่เกี่ยวข้อง</a>
	<a data-toggle="collapse" data-target="#eng" aria-expanded="true" class="nav-link collapsed" aria-controls="eng"><img src="{{$site}}/Defaultimg/8.svg" alt="ภาษาอังกฤษ">ภาษาอังกฤษ</a>
	<p class="sub-menu collapse {{ Route::current()->getName() == 'eng1' || Route::current()->getName() == 'eng2' || Route::current()->getName() == 'eng3' || Route::current()->getName() == 'eng4'
	? "show" : "" }}" id="eng" data-parent="#accordion">
		<a href="{{ route('eng1') }}" class="nav-link submenu {{ Route::current()->getName() == 'eng1' ? "active" : "" }}">แผนการป้องกันและควบคุมโรคไม่ติดต่อ 5 ปี (พ.ศ.2560-2564)</a>
		<a href="{{ route('eng2') }}" class="nav-link submenu {{ Route::current()->getName() == 'eng2' ? "active" : "" }}">คณะกรรมการ</a>
		<a href="{{ route('eng3') }}" class="nav-link submenu {{ Route::current()->getName() == 'eng3' ? "active" : "" }}">ผลการดำเนินงาน</a>
		<a href="{{ route('eng4') }}" class="nav-link submenu {{ Route::current()->getName() == 'eng4' ? "active" : "" }}">best pratice</a>
	</p>
	<a href="{{ route('userrole') }}" class="nav-link {{ Route::current()->getName() == 'userrole' ? "active" : "" }}"><img src="{{$site}}/Defaultimg/login-email.svg" alt="สิทธิ์การเข้าถึง">สิทธิ์การเข้าถึง</a>
	{{--<a href="{{ route('menuheader.index') }}" class="nav-link {{ Route::current()->getName() == 'menuheader.index' ? "active" : "" }}"><img src="{{$site}}/Defaultimg/link.svg">เมนู</a>--}}
</div>

resources/views/admin/navright.blade.php
<style>
	.topnav {
		background-color: #508EBF;
	}
	#logoimg{
		position: absolute;
		left: 100px;
		top: 5px;
	}
	#bg{
		position: absolute;
		left: 90px;
		width: 78px;
		height: 150px;
		background-color: white;
		background-size: 300px 300px;
		box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
		border-radius: 0px 0px 40px 40px;
	}
	.dropdown-content {
		display: none;
		position: absolute;
		background-color: white;
		min-width: 160px;
		box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
		right: -5px;
		top: 70px;
		z-index: 1;
		border: 1px solid #508EBF;
		border-radius: 5px;
	}
	.dropdown-content:before {
		content: "";
		position: absolute;
		top: -30px;
		right: 10%;
		border: 15px solid transparent;
		border-bottom-color: #508EBF;
	}
	.dropdown-content a {
		padding: 20px 16px;
		text-decoration: none;
	}
	.dropdown-content a:hover {
		color: white;
		background-color: #508EBF;
	}
</style>
<nav class="navbar navbar-expand-lg topnav">
	<div class="collapse navbar-collapse" id="navbarSupportedContent" style="z-index: 1;">
		<div id="bg"></div>
		<ul>
			<img id="logoimg" src="{{$site}}/Defaultimg/Logo.png">
		</ul>
		<ul class="navbar-nav ml-auto mt-2 mt-lg-0">
			<li class="nav-item dropdown">
				<a id="navbarDropdown" class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					{{--{{ Auth::user()->name }} <span class="caret"></span>--}}
					<img src="{{$site}}/Defaultimg/avatar-login.svg" style="margin: 0;">
				</a>
				<div class="dropdown-menu dropdown-content dropdown-menu-right" aria-labelledby="navbarDropdown">
					<a class="dropdown-item" href="{{$site}}">
						{{ __('หน้าผู้ใช้งาน') }}
					</a>
					<a class="dropdown-item" href="{{ route('admin')}}">
						{{ __('หน้าแอดมิน') }}
					</a>
					<a class="dropdown-item" href="{{ route('logout') }}"
					   tabindex="0" onclick="event.preventDefault();
						   document.getElementById('logout-form').submit();">
						{{ __('ออกจากระบบ') }}
					</a>
					<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
						@csrf
					</form>
				</div>
			</li>
		</ul>
	</div>
</nav>