routes/web.php
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Route::get('/rss', function () {
    return view('user.gl-rss');
})->name('rssfeed');


Route::get('/card-carousel', function () {
	return view('card-carousel')->with('imgslide', \App\imgslide::all());
})->name('card-carousel');


Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home/team', 'HomeController@teamview')->name('team');

//Route::group(['middleware' => ['auth']], function () {
	Route::get('/home/topic', 'topicController@index')->name('topic');
	Route::get('/home/mytopic', 'topicController@mytopic')->name('mytopic');
	Route::get('/home/topic/addtopic', 'topicController@Showaddtopics')->name('showaddtopic');
	Route::post('/home/topic/addtopic', 'topicController@addtopic')->name('addtopic');
    Route::post('/home/topic/edittopic', 'topicController@edittopic')->name('edittopic');
    Route::post('/home/topic/addcomment', 'topicController@addcomment')->name('addcomment');
    Route::get('/home/topic/{id}', 'topicController@intopic')->name('intopic');
    Route::get('/home/topic/{id}/edit', 'topicController@showedittopic')->name('showedittopic');
    Route::post('/home/topic/report', 'topicController@report')->name('report');
    Route::post('/autocomplete','topicController@autocomplete');
    Route::post('/searchcontents','contentsController@searchcontents');
    Route::post('/searchcontentseng','contentsController@searchcontentseng');
//});

Route::get('/home/media', 'contentactController@indexuser')->name('media');
Route::get('/home/new', 'contentnewController@indexuser')->name('new');
Route::get('/home/media/{id}', 'contentactController@showuser')->name('showmedia');
Route::get('/home/result', 'resultController@indexuser')->name('result');
Route::get('/home/best', 'HomeController@best')->name('best');
Route::get('/home/content', 'contentsController@indexuser')->name('content');
Route::get("/home/contentre", function(){
    return View::make("user.contentre");
})->name('contentre');
Route::get("/home/contentf", function(){
    return View::make("user.contentf");
})->name('contentf');
Route::get("/home/contentn", function(){
    return View::make("user.contentn");
})->name('contentn');
Route::get('/home/eng', 'engController@indexuser')->name('eng');
Route::get('/showchangeprofile/{id}','HomeController@showchangeprofile')->name('showchangeprofile');
Route::get('/home/topic/deletetopic/{id}', 'topicController@deletetopic')->name('deletetopic');
Route::post('/changeprofile','HomeController@changeprofile')->name('changeprofile');

Route::group(['middleware' => ['admin']], function () {
	Route::get('/admin','adminController@index')->name('admin');
	Route::resource('/admin/contents','contentsController');
	Route::resource('/admin/contentact','contentactController');
	Route::resource('/admin/badwords','badwordController');
	Route::resource('/admin/menuheader','menuheaderController');
	Route::resource('/admin/best','bestController');
	Route::resource('/admin/contentnew','contentnewController');
	Route::get('/contentact/deletesome/{id}/{name}','contentactController@deletesome');
	Route::resource('/admin/link','linkController');
	Route::resource('/admin/eng','engController');
	Route::resource('/admin/result','resultController');
	Route::post('/admin/result/resulttable','resultController@resulttable')->name('resulttable');
	Route::resource('/admin/topic','topicBackController');
	Route::get('/admin/topic/report/{id}','topicBackController@showreports')->name('showreports');
	Route::get('/admin/topic/report/deleted/{id}/{type}','topicBackController@deletereports')->name('deletereports');
	Route::resource('/admin/team','teamController');
	Route::resource('/admin/imgslide','imgslideController');
	Route::post('/admin/banner','HomeController@banner')->name('banner');
	Route::delete('/admin/banner/{id}','HomeController@deletebanner')->name('deletebanner');
    Route::delete('/admin/contentsimg/{id}','contentsController@deleteimg');
    Route::get('/admin/homebanner', function () {
		return view('admin.homebanner');
	})->name('homebanner');
	Route::get('/admin/eng1', function () {
	    $data = \App\eng::where('category','Strategic plan')->get();
	    $img = \App\img::where('idfk','eng1')->first();
		return view('eng.index1',compact('data'),compact('img'));
	})->name('eng1');
	Route::get('/admin/eng2', function () {
        $data = \App\eng::where('category','Committee')->get();
        $img = \App\img::where('idfk','eng2')->first();
        return view('eng.index2',compact('data'),compact('img'));
    })->name('eng2');
	Route::get('/admin/eng3', function () {
        $data = \App\eng::where('category','M&E')->get();
        $img = \App\img::where('idfk','eng3')->first();
        return view('eng.index3',compact('data'),compact('img'));
    })->name('eng3');
	Route::get('/admin/eng4', function () {
        $data = \App\eng::where('category','Best practice')->get();
        $img = \App\img::where('idfk','eng4')->first();
        return view('eng.index4',compact('data'),compact('img'));
    })->name('eng4');
	Route::get('/userrole','userroleController@index')->name('userrole');
	Route::get('/userrole/delete/{id}','userroleController@delete');
	Route::get('/userrole/restore/{id}','userroleController@restore');
	Route::get('/userrole/changerole/{id}/{password}/{role}','userroleController@changerole');
	Route::get('/home/topic/closetopic/{id}', 'topicController@closetopic')->name('closetopic');
	Route::get('/home/topic/opentopic/{id}', 'topicController@opentopic')->name('opentopic');
});

Route::get('/files/{id}', 'contentactController@showpdf')->name('file.show');
Route::get('/showcontent/{id}', 'contentactController@showcontent')->name('showcontent');

Route::get('/admin/getchild/{name}','menuheaderController@getchild')->name('getchild');
Route::get('/admin/getchildinchild/{name}','menuheaderController@getchildinchild')->name('getchildinchild');

//Test page
Route::get("/test", function(){
    return View::make("test");
})->name('test');

//RSS feed
Route::get('feed/News', function() {
    $feedNews = App::make("feed");
    // cache the feed for 60 minutes with custom cache key "feedNewsKey"
    $feedNews->setCache(60, 'feedNewsKey1');
    // check if there is cached feed and build new only if is not
    if (!$feedNews->isCached()) {
    // creating rss feed with our most recent 20 records in news table
        $news = \DB::table('content_activity')->orderBy('updated_at', 'desc')->take(20)->get();
        $feedNews->title = 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข';
        $feedNews->description = 'ระบบเผยแพร่ข่าวสาร RSS';
        //        $feedNews->logo = 'http://yoursite.tld/logo.jpg';
        $feedNews->link = url('feedNews');
        $feedNews->setDateFormat('datetime'); // 'datetime', 'timestamp' or 'carbon'
        $feedNews->pubdate = $news[0]->updated_at; // date of latest news
        $feedNews->lang = 'th';
//        $feedNews->setShortening(true); // true or false if true can use setTextLimit
//        $feedNews->setTextLimit(100); // maximum length of description text
        foreach ($news as $n) {
            // set item's title, author, url, pubdate, description and content
            $feedNews->add($n->name, 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข', url('/home/media').'/'.$n->id, $n->created_at, $n->details, '');
        }
    }
    $feedNews->ctype = "text/xml";
    return $feedNews->render('rss');
});
Route::get('feed/News_activity', function() {
    $feedNews = App::make("feed");
    $feedNews->setCache(60, 'feedNewsKey2');
    if (!$feedNews->isCached()) {
        $news = \DB::table('content_activity')->where('category','ข่าวกิจกรรม')->orderBy('updated_at', 'desc')->take(20)->get();
        $feedNews->title = 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข';
        $feedNews->description = 'ระบบเผยแพร่ข่าวสาร RSS';
        $feedNews->link = url('feedNews');
        $feedNews->setDateFormat('datetime');
        $feedNews->pubdate = $news[0]->updated_at;
        $feedNews->lang = 'th';
//        $feedNews->setShortening(true);
//        $feedNews->setTextLimit(100);
        if (count($news) > 0){
            foreach ($news as $n) {
                $feedNews->add($n->name, 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข', url('/home/media').'/'.$n->id, $n->created_at, $n->details, '');
            }
        }
    }
    return $feedNews->render('rss');
});
Route::get('feed/News_release', function() {
    $feedNews = App::make("feed");
    $feedNews->setCache(60, 'feedNewsKey3');
    if (!$feedNews->isCached()) {
        $news = \DB::table('content_activity')->where('category','ข่าวประชาสัมพันธ์')->orderBy('updated_at', 'desc')->take(20)->get();
        $feedNews->title = 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข';
        $feedNews->description = 'ระบบเผยแพร่ข่าวสาร RSS';
        $feedNews->link = url('feedNews');
        $feedNews->setDateFormat('datetime');
        $feedNews->pubdate = $news[0]->updated_at;
        $feedNews->lang = 'th';
//        $feedNews->setShortening(true);
//        $feedNews->setTextLimit(100);
        if (count($news) > 0){
            foreach ($news as $n) {
                $feedNews->add($n->name, 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข', url('/home/media').'/'.$n->id, $n->created_at, $n->details, '');
            }
        }
    }
    return $feedNews->render('rss');
});
Route::get('feed/News_plan', function() {
    $feedNews = App::make("feed");
    $feedNews->setCache(60, 'feedNewsKey4');
    if (!$feedNews->isCached()) {
        $news = \DB::table('content_activity')->where('category','แผนการป้องกันและควบคุมโรคไม่ติดต่อ 5 ปี(พ.ศ. 2560-2564)')->orderBy('updated_at', 'desc')->take(20)->get();
        $feedNews->title = 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข';

app/link.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class link extends Model
{
	protected $table='link';

	protected $fillable = [
		'name','url','imguniq','edited_by'
	];

	public function img(){
		return $this->hasOne(img::class,'idfk','imguniq');
	}
}

app/Http/Controllers/linkController.php
<?php

namespace App\Http\Controllers;

use App\img;
use App\link;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use RealRashid\SweetAlert\Facades\Alert;

class linkController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
	    $data = link::with('img')->get();
	    return view('link.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
	    return view('link.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
	    try{
		    $namefkimg = date('mdYHis') . uniqid();
		    $model = link::create([
                'name' => $request['name'],
                'url' => $request['url'],
                'imguniq' => $namefkimg,
                'edited_by' => \Auth::user()->id
            ]);
		    if ($request->hasFile('img')) {
			    $name = date('mdYHis') . uniqid() . '.' . $request->file('img')->getClientOriginalExtension();
			    $destinationPath = public_path('uploads');
			    $request->file('img')->move($destinationPath, $name);
			    img::create([
				    'idfk' => $model->imguniq,
				    'path' => $name,
				    'name' => $request['img']->getClientOriginalName()
			    ]);
		    }
		    Alert::success('สำเร็จ', 'เพิ่มข้อมูลสำเร็จ');
		    return redirect()->route('link.index');
	    }catch (\Exception $e){
		    Alert::error('ล้มเหลว', 'เพิ่มข้อมูลไม่สำเร็จ');
		    return back();
	    }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
	    $model = link::where('id',$id)->with('img')->first();
	    return view('link.edit',compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
	    try{
		    $model = link::where('id',$id)->first();
		    $oldfile = img::where('idfk',$model->imguniq)->first();
		    $model->update([
			    'name' => $request->name,
			    'url' => $request->url,
                'edited_by' => \Auth::user()->id
            ]);
		    if ($request->hasFile('img')) {
			    $name = date('mdYHis') . uniqid() . '.' . $request->file('img')->getClientOriginalExtension();
			    $destinationPath = public_path('uploads');
			    $request->file('img')->move($destinationPath, $name);
			    if($oldfile){
				    File::delete(public_path() . '/uploads/' . $oldfile->path);
				    $oldfile->update([
					    'idfk' => $model->imguniq,
					    'name' => $request['img']->getClientOriginalName(),
					    'path' => $name
				    ]);
			    }else{
				    img::create([
					    'idfk' => $model->imguniq,
					    'name' => $request['img']->getClientOriginalName(),
					    'path' => $name
				    ]);
			    }
		    }
		    Alert::success('สำเร็จ', 'เปลี่ยนข้อมูลสำเร็จ');
		    return view('link.edit',compact('model'));
	    }catch (\Exception $e){
		    Alert::error('ล้มเหลว', 'เปลี่ยนข้อมูลไม่สำเร็จ');
		    return view('link.edit',compact('model'));
	    }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
	    try{
		    link::where('id',$id)->delete();
		    return response()->json(['success'=>'ลบข้อมูลสำเร็จ']);
	    }catch (\Exception $e){
		    return response()->json(['error'=>$e->getMessage()]);
	    }
    }
}

resources/views/link/create.blade.php
@extends('layouts.appadmin')
@section('content')
@include('layouts.onlyDatatable')

<form method="POST" action="{{ route('link.store') }}" enctype="multipart/form-data">
	@csrf
<div class="container py-1">
	<!--Section: Content-->
	<section class="px-md-6 mx-md-6 text-center text-lg-left dark-grey-text">
		<!--Grid row-->
		<div class="row d-flex justify-content-center">
			<!--Grid column-->
			<div class="col-md-6">
				<!-- Default form contact -->
				<form class="text-center" action="#!">
						<h3 align="center" class="font-weight-bold">เพิ่มข้อมูลเว็บไซต์</h3>
						<!-- Name -->
						<div class="md-form">
							<i role="presentation"  class="fas fa-globe-americas prefix"></i>
							<input type="text" id="name" name="name" class="form-control col-md-12" autocomplete="off" required>
							<label for="name">ชื่อเว็บไซต์</label>
						</div>
						<div class="md-form">
							<i role="presentation"  class="fas fa-link prefix"></i>
							<input type="text" id="url" name="url" class="form-control col-md-12" autocomplete="off" required>
							<label for="url">ยูอาร์แอล</label>
						</div>
						<div class="md-form">
							<div align="center">
								ตัวอย่างรูป
								<div id="previewImg"></div>
							</div>
							<div class="custom-file">
								<i role="presentation"  class="far fa-images prefix"></i>
								<input type="file" class="custom-file-input @error('img') is-invalid @enderror" id="img" name="img" onchange="preview(this);">
								<label class="custom-file-label" for="img">เลือกไฟล์รูปภาพ(4:1, 3:1, 2:1, 1:1)</label>
							</div>
						</div>
						<script type="text/javascript">
							window.preview = function (input) {
							  if (input.files && input.files[0]) {
								$("#previewImg").html("");
								$(input.files).each(function () {
								  var reader = new FileReader();
								  reader.readAsDataURL(this);
								  reader.onload = function (e) {
									$("#previewImg").append("<img class='thumb' style=\"max-height: 100px;max-width: 100px;\" src='" + e.target.result + "'>");
								  }
								});
							  }
							}
						</script>
						<button class="btn btn-info btn-block" type="submit">บันทึก</button>
				</form>
				<!-- Default form contact -->
			</div>
			<!--Grid column-->
		</div>
		<!--Grid row-->
	</section>
	<!--Section: Content-->
</div>
</form>
@endsection

resources/views/link/edit.blade.php
@extends('layouts.appadmin')
@section('content')
@include('layouts.onlyDatatable')

<form method="POST" action=" {{route('link.update',$model->id)}} " enctype="multipart/form-data">
		@csrf
		<div class="container py-1">
			<!--Section: Content-->
			<section class="px-md-6 mx-md-6 text-center text-lg-left dark-grey-text">
				<!--Grid row-->
				<div class="row d-flex justify-content-center">
					<!--Grid column-->
					<div class="col-md-6">
						<!-- Default form contact -->
						<form class="text-center" action="#!">
							<h3 align="center" class="font-weight-bold">แก้ไขข้อมูลเว็บไซต์</h3>
							<!-- Name -->
							<div class="md-form">
								<input type="text" id="name" name="name" class="form-control col-md-12" autocomplete="off" value="{{$model->name}}">
								<label for="name">ชื่อเว็บไซต์</label>
							</div>
							<div class="md-form">
								<input type="text" id="url" name="url" class="form-control col-md-12" autocomplete="off" value="{{$model->url}}">
								<label for="url">ยูอาร์แอล</label>
							</div>
							<div class="md-form">
								@if($model->img !== null)
									<div align="center">
										ตัวอย่างรูปเก่า
									</div>
									<div align="center">
										<img class='thumb' style="max-height: 100px;max-width: 100px;" src="{{$site}}/uploads/{{$model->img->path}}">
									</div>
								@endif
								<div align="center">
									ตัวอย่างรูปที่เปลี่ยน
								</div>
								<div align="center">
									<div id="previewImg"></div>
								</div>
									<div class="custom-file">
										<i role="presentation"  class="far fa-images prefix"></i>
										<input type="file" class="custom-file-input @error('img') is-invalid @enderror" id="img" name="img" onchange="preview(this);">
										<label class="custom-file-label" for="img">เลือกไฟล์รูปภาพ(4:1, 3:1, 2:1, 1:1)</label>
									</div>
								</div>
								<script type="text/javascript">
                  window.preview = function (input) {
                    if (input.files && input.files[0]) {
                      $("#previewImg").html("");
                      $(input.files).each(function () {
                        var reader = new FileReader();
                        reader.readAsDataURL(this);
                        reader.onload = function (e) {
                          $("#previewImg").append("<img class='thumb' style=\"max-height: 100px;max-width: 100px;\" src='" + e.target.result + "'>");
                        }
                      });
                    }
                  }
								</script>
							<!-- Send button -->
							{{ method_field('PUT') }}
							<button class="btn btn-info btn-block" type="submit">บันทึก</button>
						</form>
						<!-- Default form contact -->
					</div>
					<!--Grid column-->
				</div>
				<!--Grid row-->
			</section>
			<!--Section: Content-->
		</div>
	</form>
@endsection

resources/views/link/index.blade.php
@extends('layouts.appadmin')
@if(Session::has('success'))
  <div class="alert alert-success">
    <strong>Success: </strong>{{ Session::get('success') }}
  </div>
@endif
@if(Session::has('error'))
  <div class="alert alert-error">
    <strong>error: </strong>{{ Session::get('error') }}
  </div>
@endif
@section('content')
<div class="container-fluid">
<form method="get" action="{{ route('link.create') }}">
  @csrf
</form>
	<table id="example" class="table table-striped table-bordered" style="width:100%">
		<thead>
			<tr>
        <th>ไอดี</th>
        <th>ชื่อเว็บไซต์</th>
        <th>ยูอาร์แอล</th>
        <th>logo</th>
			</tr>
		</thead>
		<tbody>
		@foreach($data as $row)
			<tr>
        <td>{{$row->id}}</td>
        <td>{{$row->name}}</td>
        <td>
          <a href="{{url($row->url)}}" class="active" target="_blank">{{$row->url}}</a>
        </td>
        <td>
          @if($row->img === null)
            ไม่พบรูป
          @else
            <a class="pop">
              <img class="pop" id="imageresource" src="{{$site}}/uploads/{{$row->img->path}}" style="max-height: 100px;max-width: 100px;"/>
            </a>
          @endif
        </td>
			</tr>
		@endforeach
		</tbody>
	</table>
</div>
@endsection

@include('layouts.onlyDatatable')

<script type="text/javascript">
	var id = 0;

  $(document).ready(function() {
    var table = $('#example').DataTable({
      lengthChange: false,
      columnDefs: [
        {
          "targets": [ 0 ],
          "visible": false,
          "searchable": false
        },
      ],
      "pageLength": 10,
      "pagingType": "full_numbers",
      buttons: [
          {
          text: 'เพิ่มข้อมูล',
          action: function ( e, dt, node, config ) {
            window.location.href = './link/create';
          }
	      },
        {
          text: 'แก้ไขข้อมูล',
          action: function ( e, dt, node, config) {
            $('#example .selected').each(function() {
              window.location.href = './link/'+id[0]+'/edit';
            });
          }
        },
        {
          text: 'ลบข้อมูล',
          action: function ( e, dt, node, config) {
            $('#example .selected').each(function() {
              Swal.fire({
                title: 'คุณแน่ใจที่จะลบ ?',
                text: "โปรดดูให้แน่ใจว่าที่เลือกนั้นถูกต้อง !",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'ใช่ ลบเลย !',
                cancelButtonText : 'ยกเลิก'
              }).then((result) => {
                if (result.value) {
                  goDelete();
                  table.row('.selected').remove().draw( false );
                }
              })
            });
          }
        }
      ],
      responsive: true,
      "language": {
        "sEmptyTable":     "ไม่มีข้อมูลในตาราง",
        "sInfo":           "แสดง _START_ ถึง _END_ จาก _TOTAL_ แถว",
        "sInfoEmpty":      "แสดง 0 ถึง 0 จาก 0 แถว",
        "sInfoFiltered":   "(กรองข้อมูล _MAX_ ทุกแถว)",
        "sInfoPostFix":    "",
        "sInfoThousands":  ",",
        "sLengthMenu":     "แสดง _MENU_ แถว",
        "sLoadingRecords": "กำลังโหลดข้อมูล...",
        "sProcessing":     "กำลังดำเนินการ...",
        "sSearch":         "ค้นหา: ",
        "sZeroRecords":    "ไม่พบข้อมูล",
        "oPaginate": {
          "sFirst":    "หน้าแรก",
          "sPrevious": "ก่อนหน้า",
          "sNext":     "ถัดไป",
          "sLast":     "หน้าสุดท้าย"
        },
        "oAria": {
          "sSortAscending":  ": เปิดใช้งานการเรียงข้อมูลจากน้อยไปมาก",
          "sSortDescending": ": เปิดใช้งานการเรียงข้อมูลจากมากไปน้อย"
        }
      },
    });

    table.buttons().container().appendTo( '#example_wrapper .col-md-6:eq(0)' );

    $('#example tbody').on( 'click', 'tr', function () {
      if ( $(this).hasClass('selected') ) {
        $(this).removeClass('selected');
      }
      else {
        table.$('tr.selected').removeClass('selected');
        $(this).addClass('selected');
      }
    } );

    $('#example').on( 'click', 'tr', function () {
      id = table.row( this ).data();
    } );

  } );

  function goDelete() {
    var _token = $('input[name="_token"]').val();
    $.ajax(
      {
        type: "DELETE",
        url: "{{ route('link.store') }}"+'/'+id[0],
        data:{ _token:_token  },
          success: function (data) {
            Swal.fire({
              position: 'top-end',
              icon: 'success',
              title: 'ข้อมูลถูกลบแล้ว',
              showConfirmButton: false,
              timer: 3000
            })
          },
          error: function (data) {
          console.log(data);
            Swal.fire({
              icon: 'error',
              title: 'อุ๊บบ...',
              text: 'มีบางอย่างผิดพลาด !'
            })
        }
      });
  }
</script>