routes/web.php
	return view('card-carousel')->with('imgslide', \App\imgslide::all());
})->name('card-carousel');


Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home/team', 'HomeController@teamview')->name('team');

//Route::group(['middleware' => ['auth']], function () {
	Route::get('/home/topic', 'topicController@index')->name('topic');
	Route::get('/home/mytopic', 'topicController@mytopic')->name('mytopic');
	Route::get('/home/topic/addtopic', 'topicController@Showaddtopics')->name('showaddtopic');
	Route::post('/home/topic/addtopic', 'topicController@addtopic')->name('addtopic');
    Route::post('/home/topic/edittopic', 'topicController@edittopic')->name('edittopic');
    Route::post('/home/topic/addcomment', 'topicController@addcomment')->name('addcomment');
    Route::get('/home/topic/{id}', 'topicController@intopic')->name('intopic');
    Route::get('/home/topic/{id}/edit', 'topicController@showedittopic')->name('showedittopic');
    Route::post('/home/topic/report', 'topicController@report')->name('report');
    Route::post('/autocomplete','topicController@autocomplete');
    Route::post('/searchcontents','contentsController@searchcontents');
    Route::post('/searchcontentseng','contentsController@searchcontentseng');
//});

Route::get('/home/media', 'contentactController@indexuser')->name('media');
Route::get('/home/new', 'contentnewController@indexuser')->name('new');
Route::get('/home/media/{id}', 'contentactController@showuser')->name('showmedia');
Route::get('/home/result', 'resultController@indexuser')->name('result');
Route::get('/home/best', 'HomeController@best')->name('best');
Route::get('/home/content', 'contentsController@indexuser')->name('content');
Route::get("/home/contentre", function(){
    return View::make("user.contentre");
})->name('contentre');
Route::get("/home/contentf", function(){
    return View::make("user.contentf");
})->name('contentf');
Route::get("/home/contentn", function(){
    return View::make("user.contentn");
})->name('contentn');
Route::get('/home/eng', 'engController@indexuser')->name('eng');
Route::get('/showchangeprofile/{id}','HomeController@showchangeprofile')->name('showchangeprofile');
Route::get('/home/topic/deletetopic/{id}', 'topicController@deletetopic')->name('deletetopic');
Route::post('/changeprofile','HomeController@changeprofile')->name('changeprofile');

Route::group(['middleware' => ['admin']], function () {
	Route::get('/admin','adminController@index')->name('admin');
	Route::resource('/admin/contents','contentsController');
	Route::resource('/admin/contentact','contentactController');
	Route::resource('/admin/badwords','badwordController');
	Route::resource('/admin/menuheader','menuheaderController');
	Route::resource('/admin/best','bestController');
	Route::resource('/admin/contentnew','contentnewController');
	Route::get('/contentact/deletesome/{id}/{name}','contentactController@deletesome');
	Route::resource('/admin/link','linkController');
	Route::resource('/admin/eng','engController');
	Route::resource('/admin/result','resultController');
	Route::post('/admin/result/resulttable','resultController@resulttable')->name('resulttable');
	Route::resource('/admin/topic','topicBackController');
	Route::get('/admin/topic/report/{id}','topicBackController@showreports')->name('showreports');
	Route::get('/admin/topic/report/deleted/{id}/{type}','topicBackController@deletereports')->name('deletereports');
	Route::resource('/admin/team','teamController');
	Route::resource('/admin/imgslide','imgslideController');
	Route::post('/admin/banner','HomeController@banner')->name('banner');
	Route::delete('/admin/banner/{id}','HomeController@deletebanner')->name('deletebanner');
    Route::delete('/admin/contentsimg/{id}','contentsController@deleteimg');
    Route::get('/admin/homebanner', function () {
		return view('admin.homebanner');
	})->name('homebanner');
	Route::get('/admin/eng1', function () {
	    $data = \App\eng::where('category','Strategic plan')->get();
	    $img = \App\img::where('idfk','eng1')->first();
		return view('eng.index1',compact('data'),compact('img'));
	})->name('eng1');
	Route::get('/admin/eng2', function () {
        $data = \App\eng::where('category','Committee')->get();
        $img = \App\img::where('idfk','eng2')->first();
        return view('eng.index2',compact('data'),compact('img'));
    })->name('eng2');
	Route::get('/admin/eng3', function () {
        $data = \App\eng::where('category','M&E')->get();
        $img = \App\img::where('idfk','eng3')->first();
        return view('eng.index3',compact('data'),compact('img'));
    })->name('eng3');
	Route::get('/admin/eng4', function () {
        $data = \App\eng::where('category','Best practice')->get();
        $img = \App\img::where('idfk','eng4')->first();
        return view('eng.index4',compact('data'),compact('img'));
    })->name('eng4');
	Route::get('/userrole','userroleController@index')->name('userrole');
	Route::get('/userrole/delete/{id}','userroleController@delete');
	Route::get('/userrole/restore/{id}','userroleController@restore');
	Route::get('/userrole/changerole/{id}/{password}/{role}','userroleController@changerole');
	Route::get('/home/topic/closetopic/{id}', 'topicController@closetopic')->name('closetopic');
	Route::get('/home/topic/opentopic/{id}', 'topicController@opentopic')->name('opentopic');
});

Route::get('/files/{id}', 'contentactController@showpdf')->name('file.show');
Route::get('/showcontent/{id}', 'contentactController@showcontent')->name('showcontent');

Route::get('/admin/getchild/{name}','menuheaderController@getchild')->name('getchild');
Route::get('/admin/getchildinchild/{name}','menuheaderController@getchildinchild')->name('getchildinchild');

//Test page
Route::get("/test", function(){
    return View::make("test");
})->name('test');

//RSS feed
Route::get('feed/News', function() {
    $feedNews = App::make("feed");
    // cache the feed for 60 minutes with custom cache key "feedNewsKey"
    $feedNews->setCache(60, 'feedNewsKey1');
    // check if there is cached feed and build new only if is not
    if (!$feedNews->isCached()) {
    // creating rss feed with our most recent 20 records in news table
        $news = \DB::table('content_activity')->orderBy('updated_at', 'desc')->take(20)->get();
        $feedNews->title = 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข';
        $feedNews->description = 'ระบบเผยแพร่ข่าวสาร RSS';
        //        $feedNews->logo = 'http://yoursite.tld/logo.jpg';
        $feedNews->link = url('feedNews');
        $feedNews->setDateFormat('datetime'); // 'datetime', 'timestamp' or 'carbon'
        $feedNews->pubdate = $news[0]->updated_at; // date of latest news
        $feedNews->lang = 'th';
//        $feedNews->setShortening(true); // true or false if true can use setTextLimit
//        $feedNews->setTextLimit(100); // maximum length of description text
        foreach ($news as $n) {
            // set item's title, author, url, pubdate, description and content
            $feedNews->add($n->name, 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข', url('/home/media').'/'.$n->id, $n->created_at, $n->details, '');
        }
    }
    $feedNews->ctype = "text/xml";
    return $feedNews->render('rss');
});
Route::get('feed/News_activity', function() {
    $feedNews = App::make("feed");
    $feedNews->setCache(60, 'feedNewsKey2');
    if (!$feedNews->isCached()) {
        $news = \DB::table('content_activity')->where('category','ข่าวกิจกรรม')->orderBy('updated_at', 'desc')->take(20)->get();
        $feedNews->title = 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข';
        $feedNews->description = 'ระบบเผยแพร่ข่าวสาร RSS';
        $feedNews->link = url('feedNews');
        $feedNews->setDateFormat('datetime');
        $feedNews->pubdate = $news[0]->updated_at;
        $feedNews->lang = 'th';
//        $feedNews->setShortening(true);
//        $feedNews->setTextLimit(100);
        if (count($news) > 0){
            foreach ($news as $n) {
                $feedNews->add($n->name, 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข', url('/home/media').'/'.$n->id, $n->created_at, $n->details, '');
            }
        }
    }
    return $feedNews->render('rss');
});
Route::get('feed/News_release', function() {
    $feedNews = App::make("feed");
    $feedNews->setCache(60, 'feedNewsKey3');
    if (!$feedNews->isCached()) {
        $news = \DB::table('content_activity')->where('category','ข่าวประชาสัมพันธ์')->orderBy('updated_at', 'desc')->take(20)->get();
        $feedNews->title = 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข';
        $feedNews->description = 'ระบบเผยแพร่ข่าวสาร RSS';
        $feedNews->link = url('feedNews');
        $feedNews->setDateFormat('datetime');
        $feedNews->pubdate = $news[0]->updated_at;
        $feedNews->lang = 'th';
//        $feedNews->setShortening(true);
//        $feedNews->setTextLimit(100);
        if (count($news) > 0){
            foreach ($news as $n) {
                $feedNews->add($n->name, 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข', url('/home/media').'/'.$n->id, $n->created_at, $n->details, '');
            }
        }
    }
    return $feedNews->render('rss');
});
Route::get('feed/News_plan', function() {
    $feedNews = App::make("feed");
    $feedNews->setCache(60, 'feedNewsKey4');
    if (!$feedNews->isCached()) {
        $news = \DB::table('content_activity')->where('category','แผนการป้องกันและควบคุมโรคไม่ติดต่อ 5 ปี(พ.ศ. 2560-2564)')->orderBy('updated_at', 'desc')->take(20)->get();
        $feedNews->title = 'กองโรคไม่ติดต่อ กรมควบคุมโรค กระทรวงสาธารณสุข';
        $feedNews->description = 'ระบบเผยแพร่ข่าวสาร RSS';
        $feedNews->link = url('feedNews');
        $feedNews->setDateFormat('datetime');
        $feedNews->pubdate = $news[0]->updated_at;

app/Http/Controllers/topicBackController.php
<?php

namespace App\Http\Controllers;

use App\comments;
use App\reports;
use App\topics;
use function compact;
use function dd;
use Exception;
use Illuminate\Http\Request;
use function response;
use function view;

class topicBackController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('topicback.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        dd('t');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = topics::where('id',$id)->firstorfail();
        return view('topicback.details',compact('data'));
    }

    public function showreports($id)
    {
        $data = reports::where('idreport',$id)->get();
        return view('topicback.reports',compact('data'));
    }

    public function deletereports($id,$type)
    {
        try{
            switch ($type){
                case 'comments':{
                    comments::where('id',$id)->first()->delete();
                    reports::where('idreport',$id)->delete();
                    break;
                }
                case 'topics':{
                    topics::where('id',$id)->first()->delete();
                    comments::where('topicid',$id)->delete();
                    reports::where('idreport',$id)->delete();
                    break;
                }
                case 'ไม่สนใจ':{
                    reports::where('idreport',$id)->delete();
                    break;
                }
            }
            return response()->json(['success'=>'ลบสำเร็จ']);
        }catch (Exception $e){
            return response()->json(['error'=>$e->getMessage()]);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        dd('t');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
            topics::where('id',$id)->first()->delete();
            return response()->json(['success'=>$id]);
        }catch (Exception $e){
            return response()->json(['error'=>$e->getMessage()]);
        }
    }
}

resources/views/topicback/badword.blade.php
<style>
    .flex-container {
        display: flex;
        flex-wrap: wrap;
        border: 1px solid grey;
        border-radius: 20px;
    }

    .flex-container > button {
        margin: 5px;
        min-width: 50px;
        text-align: center;
        line-height: 12px;
        font-size: 14px;
        border-radius: 20px;
        height: 30px;
        background-color: transparent;
        border: 1px solid black;
        box-shadow: none;
    }

    .flex-container > button:hover{
        background-color: red;
    }
</style>
<?php
$data = \App\badwords::all();
?>
<div class="container-fluid">
    <div class="row">
        <h2>แบนคำที่ไม่ต้องการให้แสดง(คลิกเพื่อลบ)</h2>
        <div class="col-9">
            <br/>
            <div class="flex-container">
                @foreach($data as $item)
                    <button tabindex="0" onclick="deletesome('{{$item->id}}');">{{$item->badword}}</button>
                @endforeach
            </div>
        </div>
        <div class="col-3">
            <form method="POST" action="{{ route('badwords.store') }}" enctype="multipart/form-data">
                @csrf
                <h5>เพิ่มคำแบน</h5>
                <div class="md-form">
                    <input type="text" id="badword" name="badword" class="form-control col-12"
                           list="badwordlist" autocomplete="off" value="{{ old('badwordlist') }}" required>
                    <label for="badword">คำที่ต้องการแบน</label>
                    <datalist id="badwordlist">
                        @foreach($data as $option)
                            <option>{{$option->badword}}</option>
                        @endforeach
                    </datalist>
                </div>
                <button class="btn col-12">เพิ่ม</button>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    function deletesome(id) {
        var _token = $('input[name="_token"]').val();
        Swal.fire({
            title: 'คุณแน่ใจที่จะลบ ?',
            text: "โปรดดูให้แน่ใจว่าที่เลือกนั้นถูกต้อง !",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'ใช่ ลบเลย !',
            cancelButtonText : 'ยกเลิก'
        }).then((result) => {
            if (result.value) {
                $.ajax(
                    {
                        type: "DELETE",
                        url: "{{ route('badwords.store') }}"+'/'+id,
                        data:{ _token:_token  },
                        success: function (data) {
                            Swal.fire({
                                position: 'top-end',
                                icon: 'success',
                                title: 'ข้อมูลถูกลบแล้ว',
                                showConfirmButton: false,
                                timer: 3000
                            });
                            setTimeout(function(){ window.location.reload(); }, 1000);
                        },
                        error: function (data) {
                            console.log(data);
                            Swal.fire({
                                icon: 'error',
                                title: 'อุ๊บบ...',
                                text: 'มีบางอย่างผิดพลาด !'
                            })
                        }
                    });
            }
        })

    }
</script>

resources/views/topicback/create.blade.php
@extends('layouts.appadmin')
@section('content')
<form method="POST" action="{{ route('result.store') }}" enctype="multipart/form-data">
	@csrf
	<div class="container py-1">
		<!--Section: Content-->
		<section class="px-md-6 mx-md-6 text-center text-lg-left dark-grey-text">
			<!--Grid row-->
			<div class="row d-flex justify-content-center">
				<!--Grid column-->
				<div class="col-md-12">
					<!-- Default form contact -->
					<form class="text-center" action="#!">

						<!-- Send button -->
						<button class="btn btn-info btn-block" type="submit">บันทึก</button>
						<!-- Basic dropdown -->
					</form>
					<!-- Default form contact -->
				</div>
				<!--Grid column-->
			</div>
			<!--Grid row-->
		</section>
		<!--Section: Content-->
	</div>

</form>
@endsection

resources/views/topicback/details.blade.php
@extends('layouts.appadmin')
@section('content')
    <h1 style="font-weight: bold">การจัดการกระดานสนทนา</h1>
    <hr style="border: 1px solid #B6C3C6;">

    <div class="row">
        <div class="col-5"><span style="float: right">ผู้สร้าง :</span></div>
        <div class="col-7"><span>{{$data->users->name}}</span></div>
        <div class="col-5"><span style="float: right">รหัสผู้ดูแล :</span></div>
        <div class="col-7"><span>{{$data->users->name}}</span></div>
        <div class="col-5"><span style="float: right">สถานะ :</span></div>
        <div class="col-7"><span>{{$data->users->role}}</span></div>
    </div>
    <hr style="border: 1px solid #B6C3C6;">

    <div class="row">
        <div class="col-5"><span style="float: right">หัวข้อคำถาม :</span></div>
        <div class="col-7"><span>{{$data->name}}</span></div>
        <div class="col-5"><span style="float: right">หมวดหมู่ :</span></div>
        <div class="col-7"><span>{{$data->getcategory()}}</span></div>
        <div class="col-5"><span style="float: right">หมวดหมู่ย่อย :</span></div>
        <div class="col-7"><span>{{($data->subcategory != null ? $data->getsubcategory():'-')}}</span></div>
        <div class="col-6 offset-2 text-center"><span>รายละเอียด</span></div>
        <div class="col-7 offset-2" style="border: 1px solid #B6C3C6;"><span>{!! $data->details !!}</span></div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="float-right">
                <a class="btn" tabindex="0" onclick="window.open('{{{$site.'/home/topic/'.$data->id}}}');" style="border-radius: 40px;color: black;background-color: white;border: 1px solid #B6C3C6;box-shadow: none">ไปที่การสนทนานี้</a>
                <a class="btn" tabindex="0" onclick="confirmdelete('{{$data->id}}');" style="border-radius: 40px;color: black;background-color: white;border: 1px solid #B6C3C6;box-shadow: none">ยืนยันการลบ</a>
            </div>
        </div>
    </div>
@endsection
<script>
    function confirmdelete(id) {
        Swal.fire({
            title: 'คุณแน่ใจที่จะลบ ?',
            text: "กระดานสนทนาจะหายไป !",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'ใช่ ลบเลย !',
            cancelButtonText : 'ยกเลิก'
        }).then((result) => {
            if (result.value) {
                deleted(id);
            }
        })
    };

    function deleted(id) {
        let _token = $('input[name="_token"]').val();
        if(id){
            $.ajax(
                {
                    type: "DELETE",
                    url: "{{ route('topic.store') }}"+'/'+id,
                    data:{ _token:_token  },
                    success: function (data) {
                        console.log(data);
                        Swal.fire({
                            position: 'top-end',
                            icon: 'success',
                            title: 'ข้อมูลถูกลบแล้ว',
                            showConfirmButton: false,
                            timer: 3000
                        });
                        setTimeout(function(){ window.location.href = '{{route('topic.index')}}'; }, 1000);
                    },
                    error: function (data) {
                        console.log(data);
                        Swal.fire({
                            icon: 'error',
                            title: data.error,
                            text: 'มีบางอย่างผิดพลาด !'
                        })
                    }
                });
        }
    };
</script>

resources/views/topicback/edit.blade.php
@extends('layouts.appadmin')
@section('content')
	<form method="POST" action="{{ route('result.update',$data->id) }}" enctype="multipart/form-data">
		@csrf
		<div class="container py-1">
			<!--Section: Content-->
			<section class="px-md-6 mx-md-6 text-center text-lg-left dark-grey-text">
				<!--Grid row-->
				<div class="row d-flex justify-content-center">
					<!--Grid column-->
					<div class="col-md-12">
						<!-- Default form contact -->
						<form class="text-center" action="#!">

							<!-- Send button -->
							{{method_field('PUT')}}
							<button class="btn btn-info btn-block" type="submit">บันทึก</button>
							<!-- Basic dropdown -->
						</form>
						<!-- Default form contact -->
					</div>
					<!--Grid column-->
				</div>
				<!--Grid row-->
			</section>
			<!--Section: Content-->
		</div>

	</form>
@endsection

resources/views/topicback/reports.blade.php
@extends('layouts.appadmin')
@section('content')
<div class="container-fluid">

    {{--<h1 style="font-weight: bold">การจัดการรายงานปัญหา</h1>--}}
    {{--<hr style="border: 1px solid #B6C3C6;">--}}


    @foreach($data as $index => $row)
    @if($loop->first)
        <div class="row">
            <div class="col-5"><span style="float: right">ผู้สร้าง :</span></div>
            <div class="col-7"><span>
                {{$row->type == 'comments'?$row->reports->topic->users->name:$row->reports->users->name}}
            </span></div>
            <div class="col-5"><span style="float: right">รหัสผู้ดูแล :</span></div>
            <div class="col-7"><span>
                {{$row->type == 'comments'?$row->reports->topic->users->name:$row->reports->users->name}}
            </span></div>
            <div class="col-5"><span style="float: right">สถานะ :</span></div>
            <div class="col-7"><span>
                {{$row->type == 'comments'?$row->reports->topic->users->role:$row->reports->users->role}}
            </span></div>
            <div class="col-9 offset-1">
                <hr style="border: 1px solid #B6C3C6;">
            </div>
        </div>
    @endif

    <div class="row">
        <div class="col-5"><span style="float: right">หัวข้อที่ :</span></div>
        <div class="col-7"><span>{{$index+1}}</span></div>
        <div class="col-5"><span style="float: right">เหตุผลที่ถูกรายงาน :</span></div>
        <div class="col-7"><span>{{$row->details}}</span></div>
        @if($row->type == 'comments')
            <div class="col-5"><span style="float: right">หมวดหมู่ :</span></div>
            <div class="col-7"><span>การตอบกลับ</span></div>
        @else
            <div class="col-5"><span style="float: right">หัวข้อที่ถูกรายงาน :</span></div>
            <div class="col-7"><span>{!! $row->getname()->name !!}</span></div>
            <div class="col-5"><span style="float: right">หมวดหมู่ :</span></div>
            <div class="col-7"><span>{{$row->reports->getcategory()}}</span></div>
            <div class="col-5"><span style="float: right">หมวดหมู่ย่อย :</span></div>
            <div class="col-7"><span>{{$row->reports->getsubcategory()}}</span></div>
        @endif
        <div class="col-9 offset-1">
            <hr style="border: 1px solid #B6C3C6;">
        </div>
        @if($loop->last)
            <div class="col-6 offset-2 text-center"><span>รายละเอียด</span></div>
            <div class="col-7 offset-2" style="border: 1px solid #B6C3C6;"><span>{!!
            $row->type == 'comments'?$row->reports->message:$row->reports->details
        !!}</span></div>
            <div class="col-12">
                <div class="float-right">
                    <a class="btn" onclick="confirmcancle('{{$data[0]->idreport}}','ไม่สนใจ');" style="border-radius: 40px;color: black;border: 1px solid #B6C3C6;box-shadow: none;">ไม่สนใจ</a>
                    <a class="btn" onclick="confirmdelete('{{$data[0]->idreport}}','{{$data[0]->type}}');" style="border-radius: 40px;color: black;border: 1px solid #B6C3C6;box-shadow: none;">ยืนยันการลบ</a>
                </div>
            </div>
        @endif
    </div>

@endforeach
</div>

@endsection

<script>
    function confirmcancle(id,type) {
        Swal.fire({
            title: 'คุณแน่ใจที่จะไม่สนใจ ?',
            text: "ข้อมูลจะยังคงอยู่ !",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'ใช่ ยืนยัน !',
            cancelButtonText : 'ยกเลิก'
        }).then((result) => {
            if (result.value) {
                deleted(id,type);
            }
        })
    };

    function confirmdelete(id,type) {
        Swal.fire({
            title: 'คุณแน่ใจที่จะลบ ?',
            text: "ข้อมูลที่ถูกรายงานจะถูกลบ !",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'ใช่ ลบเลย !',
            cancelButtonText : 'ยกเลิก'
        }).then((result) => {
            if (result.value) {
                deleted(id,type);
            }
        })
    };

    function deleted(id,type) {
        let _token = $('input[name="_token"]').val();
        if(id){
            $.ajax(
                {
                    type: "get",
                    url: '{{$site.'/admin/topic/report/deleted/'}}'+id+'/'+type,
                    data:{ _token:_token  },
                    success: function (data) {
                        Swal.fire({
                            position: 'top-end',
                            icon: 'success',
                            title: 'ข้อมูลถูกลบแล้ว',
                            showConfirmButton: false,
                            timer: 3000
                        });
                        setTimeout(function(){ window.location.href = '{{route('topic.index')}}'; }, 1000);
                    },
                    error: function (data) {
                        console.log(data);
                        Swal.fire({
                            icon: 'error',
                            title: data.error,
                            text: 'มีบางอย่างผิดพลาด !'
                        })
                    }
                });
        }
    };
</script>